name: Backup development (nightly)
on:
  schedule:
    # UTC
    - cron: '00 7 * * *'
  workflow_dispatch:
jobs:
  backup:
    uses: libops/actions/.github/workflows/backup.yml@main
    with:
      environment: development
    permissions:
      contents: read
      id-token: write
    secrets: inherit
